version: "3.8"

services:
  discord-bot:
    container_name: discord-bot
    build: app
    restart: always
    volumes:
      - ./assets:/usr/assets/
      - ./cogs:/usr/src/app/cogs
      - ./cogs.json:/usr/src/app/cogs.json
      - ./configuration.json:/usr/src/app/configuration.json
    networks:
      - bot-network # Network to connect to if you want to communicate to other containers in a cog

networks:
  bot-network:
    driver: bridge
